version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webb:
    build:
      context: ./WebbApplikation
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Database=mydb;Username=postgres;Password=postgres"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
